// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "finance"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  TDepositWithdraw selectDepositWithdrawByPrimaryKey(string traceId, i32 id)")
  fmt.Fprintln(os.Stderr, "  bool auditDepositWithdraw(string traceId, string status, string mark, i32 withdrawId)")
  fmt.Fprintln(os.Stderr, "   selectDepositWithdrawByConditions(TDepositWithdrawParams params)")
  fmt.Fprintln(os.Stderr, "  i32 selectDepositWithdrawCountByConditions(TDepositWithdrawParams params)")
  fmt.Fprintln(os.Stderr, "   selectSlaveDepositListByConditions(TDepositWithdrawParams params)")
  fmt.Fprintln(os.Stderr, "  i32 selectSlaveDepositCountByConditions(TDepositWithdrawParams params)")
  fmt.Fprintln(os.Stderr, "   selectSlaveWithdrawListByConditions(TDepositWithdrawParams params)")
  fmt.Fprintln(os.Stderr, "  i32 selectSlaveWithdrawLCountByConditions(TDepositWithdrawParams params)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := finance.NewTDepositWithdrawServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "selectDepositWithdrawByPrimaryKey":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectDepositWithdrawByPrimaryKey requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err22 := (strconv.Atoi(flag.Arg(2)))
    if err22 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectDepositWithdrawByPrimaryKey(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "auditDepositWithdraw":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "AuditDepositWithdraw requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    tmp3, err26 := (strconv.Atoi(flag.Arg(4)))
    if err26 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.AuditDepositWithdraw(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "selectDepositWithdrawByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectDepositWithdrawByConditions requires 1 args")
      flag.Usage()
    }
    arg27 := flag.Arg(1)
    mbTrans28 := thrift.NewTMemoryBufferLen(len(arg27))
    defer mbTrans28.Close()
    _, err29 := mbTrans28.WriteString(arg27)
    if err29 != nil {
      Usage()
      return
    }
    factory30 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt31 := factory30.GetProtocol(mbTrans28)
    argvalue0 := finance.NewTDepositWithdrawParams()
    err32 := argvalue0.Read(jsProt31)
    if err32 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectDepositWithdrawByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectDepositWithdrawCountByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectDepositWithdrawCountByConditions requires 1 args")
      flag.Usage()
    }
    arg33 := flag.Arg(1)
    mbTrans34 := thrift.NewTMemoryBufferLen(len(arg33))
    defer mbTrans34.Close()
    _, err35 := mbTrans34.WriteString(arg33)
    if err35 != nil {
      Usage()
      return
    }
    factory36 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt37 := factory36.GetProtocol(mbTrans34)
    argvalue0 := finance.NewTDepositWithdrawParams()
    err38 := argvalue0.Read(jsProt37)
    if err38 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectDepositWithdrawCountByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectSlaveDepositListByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectSlaveDepositListByConditions requires 1 args")
      flag.Usage()
    }
    arg39 := flag.Arg(1)
    mbTrans40 := thrift.NewTMemoryBufferLen(len(arg39))
    defer mbTrans40.Close()
    _, err41 := mbTrans40.WriteString(arg39)
    if err41 != nil {
      Usage()
      return
    }
    factory42 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt43 := factory42.GetProtocol(mbTrans40)
    argvalue0 := finance.NewTDepositWithdrawParams()
    err44 := argvalue0.Read(jsProt43)
    if err44 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectSlaveDepositListByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectSlaveDepositCountByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectSlaveDepositCountByConditions requires 1 args")
      flag.Usage()
    }
    arg45 := flag.Arg(1)
    mbTrans46 := thrift.NewTMemoryBufferLen(len(arg45))
    defer mbTrans46.Close()
    _, err47 := mbTrans46.WriteString(arg45)
    if err47 != nil {
      Usage()
      return
    }
    factory48 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt49 := factory48.GetProtocol(mbTrans46)
    argvalue0 := finance.NewTDepositWithdrawParams()
    err50 := argvalue0.Read(jsProt49)
    if err50 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectSlaveDepositCountByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectSlaveWithdrawListByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectSlaveWithdrawListByConditions requires 1 args")
      flag.Usage()
    }
    arg51 := flag.Arg(1)
    mbTrans52 := thrift.NewTMemoryBufferLen(len(arg51))
    defer mbTrans52.Close()
    _, err53 := mbTrans52.WriteString(arg51)
    if err53 != nil {
      Usage()
      return
    }
    factory54 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt55 := factory54.GetProtocol(mbTrans52)
    argvalue0 := finance.NewTDepositWithdrawParams()
    err56 := argvalue0.Read(jsProt55)
    if err56 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectSlaveWithdrawListByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectSlaveWithdrawLCountByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectSlaveWithdrawLCountByConditions requires 1 args")
      flag.Usage()
    }
    arg57 := flag.Arg(1)
    mbTrans58 := thrift.NewTMemoryBufferLen(len(arg57))
    defer mbTrans58.Close()
    _, err59 := mbTrans58.WriteString(arg57)
    if err59 != nil {
      Usage()
      return
    }
    factory60 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt61 := factory60.GetProtocol(mbTrans58)
    argvalue0 := finance.NewTDepositWithdrawParams()
    err62 := argvalue0.Read(jsProt61)
    if err62 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectSlaveWithdrawLCountByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
