// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "user"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "   selectUserByConditions(TUserParams params)")
  fmt.Fprintln(os.Stderr, "  i32 selectUserCountByConditions(TUserParams params)")
  fmt.Fprintln(os.Stderr, "  bool updateUserStatusByUserId(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "  TUserInfo selectUserBaseInfoByUserId(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "  bool resetGoogleCode(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "  TUser selectUserById(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := user.NewTUserServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "selectUserByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectUserByConditions requires 1 args")
      flag.Usage()
    }
    arg15 := flag.Arg(1)
    mbTrans16 := thrift.NewTMemoryBufferLen(len(arg15))
    defer mbTrans16.Close()
    _, err17 := mbTrans16.WriteString(arg15)
    if err17 != nil {
      Usage()
      return
    }
    factory18 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt19 := factory18.GetProtocol(mbTrans16)
    argvalue0 := user.NewTUserParams()
    err20 := argvalue0.Read(jsProt19)
    if err20 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectUserByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectUserCountByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectUserCountByConditions requires 1 args")
      flag.Usage()
    }
    arg21 := flag.Arg(1)
    mbTrans22 := thrift.NewTMemoryBufferLen(len(arg21))
    defer mbTrans22.Close()
    _, err23 := mbTrans22.WriteString(arg21)
    if err23 != nil {
      Usage()
      return
    }
    factory24 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt25 := factory24.GetProtocol(mbTrans22)
    argvalue0 := user.NewTUserParams()
    err26 := argvalue0.Read(jsProt25)
    if err26 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectUserCountByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "updateUserStatusByUserId":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "UpdateUserStatusByUserId requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err28 := (strconv.Atoi(flag.Arg(2)))
    if err28 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.UpdateUserStatusByUserId(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectUserBaseInfoByUserId":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectUserBaseInfoByUserId requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err30 := (strconv.Atoi(flag.Arg(2)))
    if err30 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectUserBaseInfoByUserId(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "resetGoogleCode":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ResetGoogleCode requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err32 := (strconv.Atoi(flag.Arg(2)))
    if err32 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.ResetGoogleCode(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectUserById":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectUserById requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err34 := (strconv.Atoi(flag.Arg(2)))
    if err34 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectUserById(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
