// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "user"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "   selectUserByConditions(TUserParams params)")
  fmt.Fprintln(os.Stderr, "  i32 selectUserCountByConditions(TUserParams params)")
  fmt.Fprintln(os.Stderr, "  bool updateUserStatusByUserId(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "  TUserInfo selectUserBaseInfoByUserId(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "  bool resetGoogleCode(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "  TUser selectUserById(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "  TGoogleStatusResult selectUserGoogleStatus(string traceId, i32 userId)")
  fmt.Fprintln(os.Stderr, "   selectEngineAccountListByType(string traceId, i32 type, i32 startPage, i32 pageSize)")
  fmt.Fprintln(os.Stderr, "  i32 selectEngineAccountCountByType(string traceId, i32 type)")
  fmt.Fprintln(os.Stderr, "  i32 selectSlaveAllUserCount(string traceId)")
  fmt.Fprintln(os.Stderr, "   selectSlaveRegisterCountDay(string traceId, i32 days)")
  fmt.Fprintln(os.Stderr, "   selectSlaveInviteFriendsAwardTop(string traceId, i32 top)")
  fmt.Fprintln(os.Stderr, "   selectSlaveInviteUserRelation(string traceId, i32 userId, i32 level)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := user.NewTUserServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "selectUserByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectUserByConditions requires 1 args")
      flag.Usage()
    }
    arg33 := flag.Arg(1)
    mbTrans34 := thrift.NewTMemoryBufferLen(len(arg33))
    defer mbTrans34.Close()
    _, err35 := mbTrans34.WriteString(arg33)
    if err35 != nil {
      Usage()
      return
    }
    factory36 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt37 := factory36.GetProtocol(mbTrans34)
    argvalue0 := user.NewTUserParams()
    err38 := argvalue0.Read(jsProt37)
    if err38 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectUserByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectUserCountByConditions":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectUserCountByConditions requires 1 args")
      flag.Usage()
    }
    arg39 := flag.Arg(1)
    mbTrans40 := thrift.NewTMemoryBufferLen(len(arg39))
    defer mbTrans40.Close()
    _, err41 := mbTrans40.WriteString(arg39)
    if err41 != nil {
      Usage()
      return
    }
    factory42 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt43 := factory42.GetProtocol(mbTrans40)
    argvalue0 := user.NewTUserParams()
    err44 := argvalue0.Read(jsProt43)
    if err44 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SelectUserCountByConditions(context.Background(), value0))
    fmt.Print("\n")
    break
  case "updateUserStatusByUserId":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "UpdateUserStatusByUserId requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err46 := (strconv.Atoi(flag.Arg(2)))
    if err46 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.UpdateUserStatusByUserId(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectUserBaseInfoByUserId":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectUserBaseInfoByUserId requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err48 := (strconv.Atoi(flag.Arg(2)))
    if err48 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectUserBaseInfoByUserId(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "resetGoogleCode":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ResetGoogleCode requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err50 := (strconv.Atoi(flag.Arg(2)))
    if err50 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.ResetGoogleCode(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectUserById":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectUserById requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err52 := (strconv.Atoi(flag.Arg(2)))
    if err52 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectUserById(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectUserGoogleStatus":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectUserGoogleStatus requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err54 := (strconv.Atoi(flag.Arg(2)))
    if err54 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectUserGoogleStatus(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectEngineAccountListByType":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "SelectEngineAccountListByType requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err56 := (strconv.Atoi(flag.Arg(2)))
    if err56 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err57 := (strconv.Atoi(flag.Arg(3)))
    if err57 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    tmp3, err58 := (strconv.Atoi(flag.Arg(4)))
    if err58 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.SelectEngineAccountListByType(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "selectEngineAccountCountByType":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectEngineAccountCountByType requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err60 := (strconv.Atoi(flag.Arg(2)))
    if err60 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectEngineAccountCountByType(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectSlaveAllUserCount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SelectSlaveAllUserCount requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.SelectSlaveAllUserCount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectSlaveRegisterCountDay":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectSlaveRegisterCountDay requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err63 := (strconv.Atoi(flag.Arg(2)))
    if err63 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectSlaveRegisterCountDay(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectSlaveInviteFriendsAwardTop":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectSlaveInviteFriendsAwardTop requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err65 := (strconv.Atoi(flag.Arg(2)))
    if err65 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    fmt.Print(client.SelectSlaveInviteFriendsAwardTop(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "selectSlaveInviteUserRelation":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "SelectSlaveInviteUserRelation requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err67 := (strconv.Atoi(flag.Arg(2)))
    if err67 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err68 := (strconv.Atoi(flag.Arg(3)))
    if err68 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.SelectSlaveInviteUserRelation(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
