// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
	"bisale/bisale-console-api/thrift/inputs"
	"bisale/bisale-console-api/thrift/outputs"
        "bisale/bisale-console-api/thrift/account"
)

var _ = inputs.GoUnusedProtection__
var _ = outputs.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  bool Ping()")
  fmt.Fprintln(os.Stderr, "  string Version()")
  fmt.Fprintln(os.Stderr, "  LoginOutput MobileLogin(string traceId, MobileLoginInput output)")
  fmt.Fprintln(os.Stderr, "  CreateMemberOutput CreateMember(string traceId, CreateMemberInput input)")
  fmt.Fprintln(os.Stderr, "  GetMemberOutput GetMemberByMobile(string traceId, string mobile)")
  fmt.Fprintln(os.Stderr, "  GetMemberOutput GetMemberByEmail(string traceId, string mobile)")
  fmt.Fprintln(os.Stderr, "  GetMemberOutput GetMemberByAccount(string traceId, string mobile)")
  fmt.Fprintln(os.Stderr, "  string GenerateJWTToken(string traceId, JWTInput input, string secretKey, i32 expired)")
  fmt.Fprintln(os.Stderr, "  JWTOutput ValidateJWT(string traceId, string tokenString, string secretKey)")
  fmt.Fprintln(os.Stderr, "  i32 OperateStart(string traceId, MemberOperationInput input)")
  fmt.Fprintln(os.Stderr, "  void OperateEnd(i32 id, MemberOperationInput input)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := account.NewAccountClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "Ping":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Ping requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Ping(context.Background()))
    fmt.Print("\n")
    break
  case "Version":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Version requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Version(context.Background()))
    fmt.Print("\n")
    break
  case "MobileLogin":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "MobileLogin requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg25 := flag.Arg(2)
    mbTrans26 := thrift.NewTMemoryBufferLen(len(arg25))
    defer mbTrans26.Close()
    _, err27 := mbTrans26.WriteString(arg25)
    if err27 != nil {
      Usage()
      return
    }
    factory28 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt29 := factory28.GetProtocol(mbTrans26)
    argvalue1 := inputs.NewMobileLoginInput()
    err30 := argvalue1.Read(jsProt29)
    if err30 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.MobileLogin(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "CreateMember":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "CreateMember requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg32 := flag.Arg(2)
    mbTrans33 := thrift.NewTMemoryBufferLen(len(arg32))
    defer mbTrans33.Close()
    _, err34 := mbTrans33.WriteString(arg32)
    if err34 != nil {
      Usage()
      return
    }
    factory35 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt36 := factory35.GetProtocol(mbTrans33)
    argvalue1 := inputs.NewCreateMemberInput()
    err37 := argvalue1.Read(jsProt36)
    if err37 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.CreateMember(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetMemberByMobile":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetMemberByMobile requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetMemberByMobile(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetMemberByEmail":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetMemberByEmail requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetMemberByEmail(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetMemberByAccount":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetMemberByAccount requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetMemberByAccount(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GenerateJWTToken":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "GenerateJWTToken requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg45 := flag.Arg(2)
    mbTrans46 := thrift.NewTMemoryBufferLen(len(arg45))
    defer mbTrans46.Close()
    _, err47 := mbTrans46.WriteString(arg45)
    if err47 != nil {
      Usage()
      return
    }
    factory48 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt49 := factory48.GetProtocol(mbTrans46)
    argvalue1 := inputs.NewJWTInput()
    err50 := argvalue1.Read(jsProt49)
    if err50 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    tmp3, err52 := (strconv.Atoi(flag.Arg(4)))
    if err52 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.GenerateJWTToken(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "ValidateJWT":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "ValidateJWT requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.ValidateJWT(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "OperateStart":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "OperateStart requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    arg57 := flag.Arg(2)
    mbTrans58 := thrift.NewTMemoryBufferLen(len(arg57))
    defer mbTrans58.Close()
    _, err59 := mbTrans58.WriteString(arg57)
    if err59 != nil {
      Usage()
      return
    }
    factory60 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt61 := factory60.GetProtocol(mbTrans58)
    argvalue1 := inputs.NewMemberOperationInput()
    err62 := argvalue1.Read(jsProt61)
    if err62 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.OperateStart(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "OperateEnd":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "OperateEnd requires 2 args")
      flag.Usage()
    }
    tmp0, err63 := (strconv.Atoi(flag.Arg(1)))
    if err63 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    arg64 := flag.Arg(2)
    mbTrans65 := thrift.NewTMemoryBufferLen(len(arg64))
    defer mbTrans65.Close()
    _, err66 := mbTrans65.WriteString(arg64)
    if err66 != nil {
      Usage()
      return
    }
    factory67 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt68 := factory67.GetProtocol(mbTrans65)
    argvalue1 := inputs.NewMemberOperationInput()
    err69 := argvalue1.Read(jsProt68)
    if err69 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.OperateEnd(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
