// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "captcha"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  bool Ping()")
  fmt.Fprintln(os.Stderr, "  string Version()")
  fmt.Fprintln(os.Stderr, "  NumberCode GenerateNumberCode(string traceId, string target, i32 len, i32 expired)")
  fmt.Fprintln(os.Stderr, "  bool ValidateNumberCode(string traceId, string target, string code, string token)")
  fmt.Fprintln(os.Stderr, "  void ClearNumberCode(string traceId, string token)")
  fmt.Fprintln(os.Stderr, "  ImageCode GenerateImageCode(string traceId, i32 len, i32 expired, i32 width, i32 height)")
  fmt.Fprintln(os.Stderr, "  bool ValidateImageCode(string traceId, string code, string token)")
  fmt.Fprintln(os.Stderr, "  TwoFactorCode GenerateTwoFactor(string traceId, string label, string issuer, string secret)")
  fmt.Fprintln(os.Stderr, "  bool ValidateTwoFactorCode(string traceId, string secret, string code, bool once)")
  fmt.Fprintln(os.Stderr, "  void SetCount(string traceId, string identifier, i32 times, i32 expired)")
  fmt.Fprintln(os.Stderr, "  i32 GetCount(string traceId, string identifier)")
  fmt.Fprintln(os.Stderr, "  void ClearCount(string traceId, string identifier)")
  fmt.Fprintln(os.Stderr, "  i32 GetTodayLeftSeconds(string traceId)")
  fmt.Fprintln(os.Stderr, "  void SetTimer(string traceId, string identifier, i32 expired)")
  fmt.Fprintln(os.Stderr, "  bool GetTimer(string traceId, string identifier)")
  fmt.Fprintln(os.Stderr, "  void ClearTimer(string traceId, string identifier)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := captcha.NewCaptchaClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "Ping":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Ping requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Ping(context.Background()))
    fmt.Print("\n")
    break
  case "Version":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Version requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Version(context.Background()))
    fmt.Print("\n")
    break
  case "GenerateNumberCode":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "GenerateNumberCode requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    tmp2, err36 := (strconv.Atoi(flag.Arg(3)))
    if err36 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    tmp3, err37 := (strconv.Atoi(flag.Arg(4)))
    if err37 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.GenerateNumberCode(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "ValidateNumberCode":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "ValidateNumberCode requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.ValidateNumberCode(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "ClearNumberCode":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ClearNumberCode requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ClearNumberCode(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GenerateImageCode":
    if flag.NArg() - 1 != 5 {
      fmt.Fprintln(os.Stderr, "GenerateImageCode requires 5 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    tmp1, err45 := (strconv.Atoi(flag.Arg(2)))
    if err45 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err46 := (strconv.Atoi(flag.Arg(3)))
    if err46 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    tmp3, err47 := (strconv.Atoi(flag.Arg(4)))
    if err47 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    tmp4, err48 := (strconv.Atoi(flag.Arg(5)))
    if err48 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    fmt.Print(client.GenerateImageCode(context.Background(), value0, value1, value2, value3, value4))
    fmt.Print("\n")
    break
  case "ValidateImageCode":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "ValidateImageCode requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.ValidateImageCode(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "GenerateTwoFactor":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "GenerateTwoFactor requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.GenerateTwoFactor(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "ValidateTwoFactorCode":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "ValidateTwoFactorCode requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4) == "true"
    value3 := argvalue3
    fmt.Print(client.ValidateTwoFactorCode(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "SetCount":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "SetCount requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    tmp2, err62 := (strconv.Atoi(flag.Arg(3)))
    if err62 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    tmp3, err63 := (strconv.Atoi(flag.Arg(4)))
    if err63 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.SetCount(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "GetCount":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetCount requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetCount(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "ClearCount":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ClearCount requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ClearCount(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "GetTodayLeftSeconds":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetTodayLeftSeconds requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetTodayLeftSeconds(context.Background(), value0))
    fmt.Print("\n")
    break
  case "SetTimer":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "SetTimer requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    tmp2, err71 := (strconv.Atoi(flag.Arg(3)))
    if err71 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.SetTimer(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "GetTimer":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetTimer requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetTimer(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "ClearTimer":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ClearTimer requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ClearTimer(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
