// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "content"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "   selectLangTypes()")
  fmt.Fprintln(os.Stderr, "   selectSourceTypes()")
  fmt.Fprintln(os.Stderr, "   selectStatusTypes()")
  fmt.Fprintln(os.Stderr, "  i32 addAppVersion(TAppVersion appVersion)")
  fmt.Fprintln(os.Stderr, "  i32 editAppVersion(TAppVersion appVersion)")
  fmt.Fprintln(os.Stderr, "   selectAppVersions(string version, string status, i32 startPage, i32 pageSize)")
  fmt.Fprintln(os.Stderr, "  i32 selectAppVersionCount(string version, string status)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := content.NewTAppVersionServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "selectLangTypes":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "SelectLangTypes requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.SelectLangTypes(context.Background()))
    fmt.Print("\n")
    break
  case "selectSourceTypes":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "SelectSourceTypes requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.SelectSourceTypes(context.Background()))
    fmt.Print("\n")
    break
  case "selectStatusTypes":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "SelectStatusTypes requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.SelectStatusTypes(context.Background()))
    fmt.Print("\n")
    break
  case "addAppVersion":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "AddAppVersion requires 1 args")
      flag.Usage()
    }
    arg20 := flag.Arg(1)
    mbTrans21 := thrift.NewTMemoryBufferLen(len(arg20))
    defer mbTrans21.Close()
    _, err22 := mbTrans21.WriteString(arg20)
    if err22 != nil {
      Usage()
      return
    }
    factory23 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt24 := factory23.GetProtocol(mbTrans21)
    argvalue0 := content.NewTAppVersion()
    err25 := argvalue0.Read(jsProt24)
    if err25 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.AddAppVersion(context.Background(), value0))
    fmt.Print("\n")
    break
  case "editAppVersion":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "EditAppVersion requires 1 args")
      flag.Usage()
    }
    arg26 := flag.Arg(1)
    mbTrans27 := thrift.NewTMemoryBufferLen(len(arg26))
    defer mbTrans27.Close()
    _, err28 := mbTrans27.WriteString(arg26)
    if err28 != nil {
      Usage()
      return
    }
    factory29 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt30 := factory29.GetProtocol(mbTrans27)
    argvalue0 := content.NewTAppVersion()
    err31 := argvalue0.Read(jsProt30)
    if err31 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.EditAppVersion(context.Background(), value0))
    fmt.Print("\n")
    break
  case "selectAppVersions":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "SelectAppVersions requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    tmp2, err34 := (strconv.Atoi(flag.Arg(3)))
    if err34 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    tmp3, err35 := (strconv.Atoi(flag.Arg(4)))
    if err35 != nil {
      Usage()
      return
    }
    argvalue3 := int32(tmp3)
    value3 := argvalue3
    fmt.Print(client.SelectAppVersions(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "selectAppVersionCount":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SelectAppVersionCount requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.SelectAppVersionCount(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
